"""some fix hotel model v2

Revision ID: 283f8a840024
Revises: 9fd8acff45f5
Create Date: 2024-03-25 00:16:18.751691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '283f8a840024'
down_revision: Union[str, None] = '9fd8acff45f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('hotel_id', sa.Integer(), nullable=False))
    op.drop_constraint('rooms_hotels_id_fkey', 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'hotels', ['hotel_id'], ['id'])
    op.drop_column('rooms', 'hotels_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('hotels_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key('rooms_hotels_id_fkey', 'rooms', 'hotels', ['hotels_id'], ['id'])
    op.drop_column('rooms', 'hotel_id')
    # ### end Alembic commands ###
